[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy for Warframe Market API to avoid CORS issues
[[redirects]]
  from = "/api/warframe-market/*"
  to = "https://api.warframe.market/v1/:splat"
  status = 200
  force = true
  headers = {Accept = "application/json", Language = "en", Platform = "pc"}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://aistudio.google.com https://generativelanguage.googleapis.com https://warframe.market https://api.warframe.market; img-src 'self' data: blob: https://warframe.market https://api.iconify.design; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://generativelanguage.googleapis.com https://warframe.market https://api.warframe.market;"