// Purpose: Local image management service for prime parts and sets
// Author: PlatScanner Development Team
// Last Updated: Latest

/**
 * Service for managing local prime part and set images
 * Uses the part-mapping.json file generated by download-primeparts.sh
 * Falls back to parent set images for individual prime parts
 */

// Cache for the part mapping to avoid repeated file loads
let partMappingCache: Record<string, string> | null = null;

/**
 * Loads the part-to-image mapping from the generated JSON file
 */
const loadPartMapping = async (): Promise<Record<string, string>> => {
  if (partMappingCache) {
    return partMappingCache;
  }

  try {
    const response = await fetch('/images/primeparts/part-mapping.json');
    if (!response.ok) {
      throw new Error(`Failed to load part mapping: ${response.status}`);
    }
    partMappingCache = await response.json();
    return partMappingCache!;
  } catch (error) {
    console.error('Failed to load part mapping:', error);
    return {};
  }
};

/**
 * Gets the local image URL for a prime part or set
 *
 * @param itemName - Name of the prime part or set (e.g., "Ash Prime Chassis", "Mesa Prime")
 * @returns Local image URL or fallback
 */
export const getLocalImageUrl = async (itemName: string): Promise<string> => {
  try {
    const mapping = await loadPartMapping();

    // Check if we have a direct mapping for this item (exact match)
    if (mapping[itemName]) {
      return `/images/primeparts/${mapping[itemName]}`;
    }

    // For prime sets, try to match without "Set" suffix
    const setName = itemName.replace(' Set', '');
    if (mapping[setName]) {
      return `/images/primeparts/${mapping[setName]}`;
    }

    // For prime parts, try to get the parent set image
    // e.g., "Akarius Prime Link" → "Akarius Prime" → use Akarius Prime image
    const parentSetName = getParentSetName(itemName);
    if (parentSetName !== itemName && mapping[parentSetName]) {
      console.log(`🔗 Mapping part "${itemName}" to parent image: ${parentSetName}`);
      return `/images/primeparts/${mapping[parentSetName]}`;
    }

    // Fallback: try to construct filename from item name
    const normalizedName = itemName.toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/&/g, '')
      .replace(/'/g, '');

    return `/images/primeparts/${normalizedName}.png`;
  } catch (error) {
    console.error(`Failed to get local image for ${itemName}:`, error);
    // Ultimate fallback - return unknown image
    return '/images/primeparts/unknown.png';
  }
};

/**
 * Gets the local image URL for a prime part synchronously (if mapping is cached)
 * Use this when you know the mapping is already loaded
 *
 * @param itemName - Name of the prime part or set
 * @returns Local image URL or null if mapping not cached
 */
export const getLocalImageUrlSync = (itemName: string): string | null => {
  if (!partMappingCache) {
    return null;
  }

  // Check direct mapping
  if (partMappingCache[itemName]) {
    return `/images/primeparts/${partMappingCache[itemName]}`;
  }

  // Check set name without "Set" suffix
  const setName = itemName.replace(' Set', '');
  if (partMappingCache[setName]) {
    return `/images/primeparts/${partMappingCache[setName]}`;
  }

  // For prime parts, try to get the parent set image
  const parentSetName = getParentSetName(itemName);
  if (parentSetName !== itemName && partMappingCache[parentSetName]) {
    return `/images/primeparts/${partMappingCache[parentSetName]}`;
  }

  return null;
};

/**
 * Preloads the part mapping for faster subsequent calls
 */
export const preloadPartMapping = async (): Promise<void> => {
  await loadPartMapping();
};

/**
 * Gets the parent set name for a prime part
 *
 * @param partName - Name of the prime part (e.g., "Ash Prime Chassis")
 * @returns Parent set name (e.g., "Ash Prime")
 */
export const getParentSetName = (partName: string): string => {
  // Remove common part suffixes to get the set name
  const partSuffixes = [
    'Blueprint', 'Chassis', 'Neuroptics', 'Systems',
    'Barrel', 'Receiver', 'Stock', 'Blade', 'Handle',
    'Grip', 'String', 'Link', 'Guard', 'Hilt',
    'Upper Limb', 'Lower Limb', 'Carapace', 'Cerebrum',
    'Wings', 'Harness', 'Gauntlet', 'Pouch', 'Stars',
    'Boot', 'Chain', 'Disc', 'Head', 'Ornament',
    'Band', 'Buckle', 'Blades'
  ];

  let setName = partName;

  // Sort by length (descending) to match longer suffixes first (e.g., "Upper Limb" before "Limb")
  const sortedSuffixes = partSuffixes.sort((a, b) => b.length - a.length);

  for (const suffix of sortedSuffixes) {
    if (partName.endsWith(` ${suffix}`)) {
      setName = partName.replace(` ${suffix}`, '');
      break;
    }
  }

  return setName;
};

/**
 * Checks if a local image exists for the given item
 *
 * @param itemName - Name of the item to check
 * @returns Promise<boolean> indicating if image exists
 */
export const hasLocalImage = async (itemName: string): Promise<boolean> => {
  const imageUrl = await getLocalImageUrl(itemName);

  try {
    const response = await fetch(imageUrl, { method: 'HEAD' });
    return response.ok;
  } catch {
    return false;
  }
};

export default {
  getLocalImageUrl,
  getLocalImageUrlSync,
  preloadPartMapping,
  getParentSetName,
  hasLocalImage
};